// // <auto-generated />
// using System;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using TheForge.Data;
//
// #nullable disable
//
// namespace TheForge.Migrations
// {
//     [DbContext(typeof(ForgeDbContext))]
//     partial class ForgeDbContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "8.0.4");
//
//             modelBuilder.Entity("TheForge.Data.Entities.ApiKey", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");
//
//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");
//
//                     b.Property<bool>("IsActive")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<string>("KeyHash")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("KeyHash")
//                         .IsUnique();
//
//                     b.HasIndex("UserId");
//
//                     b.ToTable("ApiKeys");
//
//                     b.HasData(
//                         new
//                         {
//                             Id = 1,
//                             CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
//                             IsActive = true,
//                             KeyHash = "c1c0e2b2d2e8f0a3c9b7d5e6f4a8b2c0d3e7f1a5b9c2d6e0f4a8b2c0d3e7f1a5",
//                             Name = "Dev key",
//                             UserId = 1
//                         });
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.UsageLog", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");
//
//                     b.Property<string>("Mode")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<string>("QueryHash")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<DateTime>("Timestamp")
//                         .HasColumnType("TEXT");
//
//                     b.Property<int>("TopK")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("UserId", "Timestamp");
//
//                     b.ToTable("UsageLogs");
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.User", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");
//
//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");
//
//                     b.Property<string>("Email")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<bool>("IsActive")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<string>("PasswordHash")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<string>("Tier")
//                         .IsRequired()
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("TEXT")
//                         .HasDefaultValue("free");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("Email")
//                         .IsUnique();
//
//                     b.ToTable("Users");
//
//                     b.HasData(
//                         new
//                         {
//                             Id = 1,
//                             CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
//                             Email = "admin@theforge.dev",
//                             IsActive = true,
//                             PasswordHash = "dev-only-not-hashed",
//                             Tier = "archmagos"
//                         });
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.UserSettings", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");
//
//                     b.Property<int?>("CandidatePool")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<string>("PreferredMode")
//                         .IsRequired()
//                         .HasColumnType("TEXT");
//
//                     b.Property<int?>("StitchingWindow")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<double?>("Temperature")
//                         .HasColumnType("REAL");
//
//                     b.Property<int?>("TopK")
//                         .HasColumnType("INTEGER");
//
//                     b.Property<DateTime>("UpdatedAt")
//                         .HasColumnType("TEXT");
//
//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");
//
//                     b.HasKey("Id");
//
//                     b.HasIndex("UserId")
//                         .IsUnique();
//
//                     b.ToTable("UserSettings");
//
//                     b.HasData(
//                         new
//                         {
//                             Id = 1,
//                             PreferredMode = "remembrancer",
//                             UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
//                             UserId = 1
//                         });
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.ApiKey", b =>
//                 {
//                     b.HasOne("TheForge.Data.Entities.User", "User")
//                         .WithMany("ApiKeys")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("User");
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.UsageLog", b =>
//                 {
//                     b.HasOne("TheForge.Data.Entities.User", "User")
//                         .WithMany("UsageLogs")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("User");
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.UserSettings", b =>
//                 {
//                     b.HasOne("TheForge.Data.Entities.User", "User")
//                         .WithOne("Settings")
//                         .HasForeignKey("TheForge.Data.Entities.UserSettings", "UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//
//                     b.Navigation("User");
//                 });
//
//             modelBuilder.Entity("TheForge.Data.Entities.User", b =>
//                 {
//                     b.Navigation("ApiKeys");
//
//                     b.Navigation("Settings");
//
//                     b.Navigation("UsageLogs");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
